In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [4]:
df = pd.read_csv('tested.csv',usecols=['Age','Fare','Survived'])

In [5]:
df.dropna(inplace=True)

In [6]:
df.head()

   Survived   Age     Fare
0         0  34.5   7.8292
1         1  47.0   7.0000
2         0  62.0   9.6875
3         0  27.0   8.6625
4         1  22.0  12.2875

In [7]:
df.shape

(331, 3)

In [10]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [11]:
x.head()

    Age     Fare
0  34.5   7.8292
1  47.0   7.0000
2  62.0   9.6875
3  27.0   8.6625
4  22.0  12.2875

In [12]:
y.head()

0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2,random_state=42)

In [15]:
x_train.head()

       Age     Fare
281   0.75  13.7750
96   76.00  78.8500
341  32.00   7.5792
18   27.00   7.9250
26   22.00  61.9792

In [17]:
clf = DecisionTreeClassifier()

In [18]:
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [19]:
y_pred = clf.predict(x_test)

In [20]:
accuracy_score(y_test,y_pred)

0.5671641791044776

In [21]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.5681818181818181)

In [22]:
kbin_age = KBinsDiscretizer(n_bins=15,encode='ordinal',strategy='quantile')
kbin_fare = KBinsDiscretizer(n_bins=15,encode='ordinal',strategy='quantile')

In [23]:
trf = ColumnTransformer([
    ('first',kbin_age,[0]),
    ('second',kbin_fare,[1])
])

In [25]:
X_train_trf = trf.fit_transform(x_train)
X_test_trf = trf.transform(x_test)

C:\Users\HP\anaconda_projects\New folder\Lib\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
C:\Users\HP\anaconda_projects\New folder\Lib\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

In [26]:
trf.named_transformers_['first'].bin_edges_

array([array([ 0.33      , 13.53333333, 18.        , 20.        , 22.        ,
              24.        , 25.2       , 27.73333333, 30.        , 32.        ,
              36.        , 39.        , 43.8       , 47.93333333, 55.        ,
              76.        ])                                                   ],
      dtype=object)

In [30]:
output = pd.DataFrame({
    'age':x_train['Age'],
    'age_trf':X_train_trf[:,0],
    'fare':x_train['Fare'],
    'fare_trf':X_train_trf[:,1]
})

In [32]:

output['age_labels'] = pd.cut(x=x_train['Age'],
                                    bins=trf.named_transformers_['first'].bin_edges_[0].tolist())
output['fare_labels'] = pd.cut(x=x_train['Fare'],
                                    bins=trf.named_transformers_['second'].bin_edges_[0].tolist())